# The API, plus the console's built assets.
#
# One service, one origin: the console's session cookie and the API that issues it belong
# together, and same-origin means no CORS on the authenticated path. The storefront is
# deliberately NOT here — see Dockerfile.storefront.

FROM node:22-slim AS base
ENV PNPM_HOME=/pnpm \
    PATH=/pnpm:$PATH \
    COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable
WORKDIR /repo

# Manifests only, so this layer is cached until a dependency actually changes. Copying the
# source first would reinstall the whole tree on every edit.
#
# Every workspace package has to be listed, not just the ones this image ships. `pnpm install`
# runs before the source arrives, so a package missing here gets no node_modules — and then
# `pnpm build`, which builds the whole workspace, compiles it without its own TypeScript or
# type definitions. That is exactly how `packages/corpus` broke both images: `Cannot find type
# definition file for 'node'`, from a package neither image ships. `scripts/check-docker.mjs`
# now fails the gate rather than letting the next new package do it again.
FROM base AS manifests
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json apps/api/
COPY apps/web/package.json apps/web/
COPY apps/storefront/package.json apps/storefront/
COPY packages/contracts/package.json packages/contracts/
COPY packages/db/package.json packages/db/
COPY packages/ui/package.json packages/ui/
COPY packages/corpus/package.json packages/corpus/
COPY packages/detect/package.json packages/detect/
COPY packages/policy/package.json packages/policy/
COPY packages/audit/package.json packages/audit/
COPY packages/narrate/package.json packages/narrate/
COPY packages/load/package.json packages/load/
COPY packages/risk-manager/package.json packages/risk-manager/

FROM manifests AS deps
RUN pnpm install --frozen-lockfile

FROM deps AS build
COPY . .
# Everything, rather than a filtered subset: Turbo orders it correctly, this stage is
# thrown away, and a filter that silently misses a shared package produces a runtime
# "cannot find module" instead of a build error.
RUN pnpm build

FROM manifests AS runtime
ENV NODE_ENV=production
# Production dependencies only. The compiled output is copied in afterwards, so nothing here
# needs a toolchain.
#
# --ignore-scripts because the root `prepare` script runs husky to install git hooks, and
# husky is a devDependency: with --prod it is not installed, the script still fires, and the
# build dies on `husky: not found`. A container has no git hooks to install. Nothing else
# here needs a lifecycle script — the one package that does, esbuild, is a devDependency and
# is absent too.
RUN pnpm install --frozen-lockfile --prod --ignore-scripts

COPY --from=build /repo/apps/api/dist apps/api/dist
# Every workspace package the API imports at runtime. `pnpm install --prod` creates the
# symlinks; without the compiled output behind them the container starts and then dies on
# "cannot find module", which is a far worse failure than not building at all.
COPY --from=build /repo/packages/contracts/dist packages/contracts/dist
COPY --from=build /repo/packages/db/dist packages/db/dist
COPY --from=build /repo/packages/corpus/dist packages/corpus/dist
COPY --from=build /repo/packages/detect/dist packages/detect/dist
COPY --from=build /repo/packages/policy/dist packages/policy/dist
COPY --from=build /repo/packages/audit/dist packages/audit/dist
COPY --from=build /repo/packages/narrate/dist packages/narrate/dist
COPY --from=build /repo/packages/load/dist packages/load/dist
COPY --from=build /repo/packages/risk-manager/dist packages/risk-manager/dist

# The policy itself, not just the code that reads it. The API refuses to start without it — the
# alternative is running on defaults nobody chose — so an image that ships the parser and not the
# file is an image that cannot boot.
COPY --from=build /repo/policy.yaml policy.yaml

# The model benchmark artefact the metrics endpoint serves. Generated by the Python pipeline, read
# by the JS server — so the file has to be in the image even though nothing in the image produces
# it. Its absence is handled gracefully (the page says "not generated"), but shipping it is the
# whole point of having a metrics page.
COPY --from=build /repo/ml/models/transaction_risk/artifacts/metrics.json      ml/models/transaction_risk/artifacts/metrics.json

# Model B's served artefacts, read by the scoring service and the metrics endpoint. The model.json
# is the linear model the request path evaluates; without it, scoring degrades to rules-only, which
# is a designed and tested path — but shipping it is the point of having a model.
COPY --from=build /repo/ml/models/incident/artifacts/model.json      ml/models/incident/artifacts/model.json
COPY --from=build /repo/ml/models/incident/artifacts/registry.json      ml/models/incident/artifacts/registry.json
COPY --from=build /repo/ml/models/incident/artifacts/metrics.json      ml/models/incident/artifacts/metrics.json

# The console, served from the same origin as the API that authenticates it. main.ts looks
# for this directory relative to the working directory and simply serves nothing if it is
# absent, so an API-only image is still valid.
COPY --from=build /repo/apps/web/dist apps/api/public

WORKDIR /repo/apps/api

# Cloud Run sandboxes the container, but there is no reason for the process to be root as
# well. Everything it needs is world-readable and it writes nothing to disk.
USER node

# No EXPOSE and no hardcoded port: Cloud Run injects PORT and the app listens on it.
CMD ["node", "dist/main.js"]
