"""The model card: what the numbers mean, and — more importantly — what they do not.

Generated from the same metrics the page renders, so the card and the numbers can never disagree.
The prose that does not depend on a number is kept short and blunt, because a model card that reads
like marketing is one nobody trusts.
"""

from __future__ import annotations


def render_model_card(metrics: dict) -> str:
    p = metrics["provenance"]
    backend = p.get("model_backend", "boosted")
    h = metrics["honest"]
    leak = metrics["leakage"]

    def band(interval: dict) -> str:
        return f"{interval['point']:.3f}  ({interval['low']:.3f}–{interval['high']:.3f})"

    return f"""# Model card — transaction risk

Generated by `make eval`. Not hand-edited; every number below is regenerated from a fixed seed.

## What this is

A calibrated histogram gradient-boosted classifier (backend: `{backend}`) that scores a card
transaction for fraud risk, over a logistic baseline it has to beat. It exists to answer one
sentence from the track: **precision and recall on labels we did not author** — measured honestly,
on a split built so the model cannot cheat.

## Data

- **Source:** `{p['data_source']}`
- {p['data_note']}
- {p['n_rows']:,} rows, {p['n_uids']:,} distinct cards, fraud rate {p['fraud_rate']:.3f}, seed {p['seed']}.

## How it was measured

The split groups whole cards together and orders them by time, with a {leak['dropped_to_gap']}-row
delay gap dropped before the test period. Grouping stops the model memorising a card and being
rewarded for it; the time order and gap stop it training on a future, and on labels that would not
yet have arrived. The test set below is cards the model never saw, from a period after it trained.

## Held-out results

| Metric | Value (95% CI) |
|---|---|
| Precision | {band(h['precision'])} |
| Recall | {band(h['recall'])} |
| PR-AUC | {band(h['pr_auc'])} |
| ROC-AUC | {h['roc_auc']:.3f} |
| Brier score | {h['brier']:.3f} (lower is better; calibration) |

Operating threshold {h['threshold']:.3f}, chosen to minimise expected cost on validation given a
missed fraud at ₹{metrics['cost']['false_negative_paise'] / 100:,.0f} and a false block at
₹{metrics['cost']['false_positive_paise'] / 100:,.0f}. The logistic baseline reaches PR-AUC
{metrics['baseline_logistic']['pr_auc']:.3f}.

## The leakage delta — why the split matters

| Split | PR-AUC | Cards shared train↔test |
|---|---|---|
| Careless (random) | {leak['naive_pr_auc']:.3f} | {leak['naive_uid_overlap']:,} |
| Honest (grouped, time-ordered) | {leak['honest_pr_auc']:.3f} | {leak['honest_uid_overlap']:,} |

A random split inflates PR-AUC by **{leak['delta']:.3f}** — the model looking better than it is,
purely by recognising cards it will not see again. The honest split is the one the headline numbers
come from. This delta is the single most important number here: it is the difference between a score
and a claim.

## Search space and budget

Deliberately small. A modest LightGBM — 300 trees, depth 6, 31 leaves, learning rate 0.05, balanced
class weights — on a handful of features, with no hyperparameter search. The point of this slice is
the honesty of the measurement, not the last point of AUC, and a large search over a small honest
test set is a good way to overfit the test set through the back door.

## What this does not claim

- On synthetic data, the absolute scores are a property of the generator, not of IEEE-CIS. The
  *method* is what transfers; the numbers are illustrative until the real file is in place.
- One merchant's view. Fraud distributed across many merchants so each sees a trickle is invisible
  here, as it is to the rest of the system.
- Calibration and threshold are frozen on a validation split from the same period; a real
  deployment would re-check both as the fraud mix drifts.
"""
