"""`METRICS.md` — the evidence for the deployed risk model, rendered from `metrics.json`.

The model card is prose about the model; this is the evidence laid out so a reviewer can read the
operating point, the per-origin breakdown and the ablation ladder without opening JSON. Generated
from the same metrics dict, so it cannot drift from what the model actually scored. Not hand-edited.
"""

from __future__ import annotations


def _interval(i: dict) -> str:
    return f"{i['point']:.3f} ({i['low']:.3f}–{i['high']:.3f})"


def _per_origin(rows: list[dict]) -> str:
    out = ["| Origin | Kind | n | Recall / FP-rate | Mean risk |", "|---|---|---|---|---|"]
    for r in rows:
        kind = "attack" if r["positive"] else "benign"
        score = (
            f"recall {r['recall']:.3f}" if r["positive"] else f"FP-rate {r['false_positive_rate']:.3f}"
        )
        out.append(f"| {r['origin']} | {kind} | {r['n']} | {score} | {r['mean_risk']:.3f} |")
    return "\n".join(out)


def _ablation(ladder: list[dict]) -> str:
    rows = [f"| {r['features']} | {r['n_features']} | {r['pr_auc']:.3f} |" for r in ladder]
    return "\n".join(["| Features | Count | PR-AUC |", "|---|---|---|", *rows])


def _reliability(points: list[dict]) -> str:
    rows = [f"| {p['predicted']:.3f} | {p['observed']:.3f} |" for p in points]
    return "\n".join(["| Predicted | Observed |", "|---|---|", *rows])


def render_metrics_md(metrics: dict) -> str:
    p = metrics["provenance"]
    h = metrics["honest"]
    leak = metrics["leakage"]

    return f"""# METRICS — card-testing risk model

Generated by `make eval`. Not hand-edited. Every number here is read from `metrics.json`, which is
deterministic from a fixed seed, so this file is a stable record rather than a snapshot of one run.

**These labels are synthetic, not real-world outcomes.** {p['data_note']}

## Headline

The deployed model, on a held-out grouped split ({metrics['split_integrity']['n_test']} entities,
{h['positives']} abuse), at the cost-optimal block threshold **{h['threshold']:.3f}**:

- PR-AUC **{_interval(h['pr_auc'])}** (no-skill floor {metrics['baseline_no_skill']['pr_auc']:.3f})
- Precision {_interval(h['precision'])}, Recall {_interval(h['recall'])}, F1 {_interval(h['f1'])}
- ROC-AUC {h['roc_auc']:.3f}, Brier {h['brier']:.3f}
- Operating point: false-decline {h['false_decline_rate']:.3f}, block-eligible {h['block_rate']:.3f},
  review band {h['review_rate']:.3f} at a {h['review_cap']:.3f} analyst budget

## Where the model is right, and where it is not

Per-origin — the honest heart of it. For attack origins the number is recall (what share it caught);
for benign origins it is the false-positive rate (what share it wrongly flagged). The model catches
obvious enumeration and the distributed case, and struggles exactly where card testing and a biller's
aggressive dunning genuinely overlap — which is the real ambiguity, not a modelling artefact.

{_per_origin(h["per_origin"])}

## Ablation ladder

What each group of features is worth, by removing the rest. The traffic-context features are what let
the model tell an outage's failures from a masked attack; drop them and that separation weakens.

{_ablation(metrics["ablation_ladder"])}

## Calibration (reliability)

Predicted risk against observed abuse rate, by decile. Close agreement is what lets the score feed a
cost-based decision rather than only a ranking.

{_reliability(h["reliability"])}

## Leakage delta

Grouped-split PR-AUC {leak['honest_pr_auc']:.3f} vs careless row-wise {leak['naive_pr_auc']:.3f}
(delta {leak['delta']:.3f}). Small on a single-generator synthetic corpus, and honestly so — the
grouped split still guarantees no scenario instance straddles train and test
({leak['honest_group_overlap']} shared groups).
"""
