"""`METRICS.md` — the three artefacts the slice is judged on, rendered from `metrics.json`.

The model card is prose about the model; this is the evidence, laid out so a reviewer can read the
ablation ladder, the risk–coverage curve and the four-class confusion matrix without opening JSON or
the console. It is generated from the same metrics dict, so it cannot drift from what the model
actually scored. Not hand-edited.
"""

from __future__ import annotations


def _confusion(classes: list[str], matrix: list[list[int]]) -> str:
    header = r"| actual \ predicted | " + " | ".join(classes) + " |"
    divider = "|" + "---|" * (len(classes) + 1)
    rows = [
        "| " + classes[i] + " | " + " | ".join(str(v) for v in row) + " |"
        for i, row in enumerate(matrix)
    ]
    return "\n".join([header, divider, *rows])


def _risk_coverage(curve: list[dict]) -> str:
    # A representative slice — every fifth threshold — so the trade is legible as a table rather
    # than a hundred near-identical rows.
    sampled = curve[::5] if len(curve) > 12 else curve
    rows = [
        f"| {r['threshold']:.3f} | {r['coverage']:.3f} | {r['selective_accuracy']:.3f} |"
        for r in sampled
    ]
    return "\n".join(
        ["| Confidence bar | Coverage | Selective accuracy |", "|---|---|---|", *rows]
    )


def _ablation(ladder: list[dict]) -> str:
    rows = [
        f"| {r['features']} | {r['n_features']} | {r['macro_f1']:.3f} |" for r in ladder
    ]
    return "\n".join(["| Features | Count | Macro-F1 |", "|---|---|---|", *rows])


def render_metrics_md(metrics: dict) -> str:
    e = metrics["evaluation"]
    h = metrics["hardening"]
    quoted = (
        h["hardened_macro_f1"]
        if h["triggered"] and h.get("hardened_macro_f1") is not None
        else e["macro_f1"]
    )

    return f"""# METRICS — incident classifier (Model B)

Generated by `make eval`. Not hand-edited. Every number here is read from `metrics.json`, which is
deterministic from a fixed seed, so this file is a stable record rather than a snapshot of one run.

Quoted macro-F1: **{quoted:.3f}** (hardened where the corpus scored above the hardening threshold —
see below). Accuracy {e['accuracy']:.3f}, abstain rate {e['abstain_rate']:.3f} at a confidence bar of
{e['abstain_threshold']}.

## Ablation ladder

What each group of features is worth, measured by removing the rest. The traffic-context features are
what separate outage from attack; drop them and that distinction collapses, which is the case for
computing population-level context at all rather than judging each entity alone.

{_ablation(metrics["ablation_ladder"])}

## Risk–coverage curve

The abstain trade. As the confidence bar rises the model answers less (coverage falls) and is right
more of what it does answer (selective accuracy rises) — the reject option turned into a curve, so
the operating point is a choice a reviewer can see rather than a hidden default.

{_risk_coverage(e["risk_coverage"])}

## Four-class confusion matrix

Rows are the actual cause, columns the predicted one; the diagonal is correct. Off-diagonal mass is
where the model confuses one cause for another — the outage/attack cell is the one that matters, and
the ablation ladder above explains what keeps it empty.

{_confusion(e["classes"], e["confusion"])}

## Corpus hardening

{'Triggered' if h['triggered'] else 'Not triggered'}. Base macro-F1 {h['base_macro_f1']:.3f}.{
    f" Above the threshold, so a round of feature noise was added and the model re-scored to "
    f"{h['hardened_macro_f1']:.3f} — the harder number quoted above." if h['triggered'] else
    " Below the hardening threshold, so the corpus was left as generated."
}
"""
