"""The model card for the deployed risk model, generated from the metrics so the two cannot disagree."""

from __future__ import annotations


def _interval(i: dict) -> str:
    return f"{i['point']:.3f} ({i['low']:.3f}–{i['high']:.3f})"


def render_model_card(metrics: dict, registry: dict) -> str:
    p = metrics["provenance"]
    h = metrics["honest"]
    leak = metrics["leakage"]
    cost = metrics["cost"]

    ablation = "\n".join(
        f"| {r['features']} | {r['n_features']} | {r['pr_auc']:.3f} |"
        for r in metrics["ablation_ladder"]
    )

    # The origins where the model is wrong most — the honest headline of a per-origin breakdown.
    def miss(row: dict) -> float:
        if row["positive"]:
            return 1.0 - (row["recall"] or 0.0)
        return row["false_positive_rate"] or 0.0

    hardest = sorted(metrics["honest"]["per_origin"], key=miss, reverse=True)[:4]
    per_origin = "\n".join(
        f"| {r['origin']} | {'attack' if r['positive'] else 'benign'} | {r['n']} | "
        f"{'recall ' + format(r['recall'], '.3f') if r['positive'] else 'FP-rate ' + format(r['false_positive_rate'], '.3f')} |"
        for r in hardest
    )

    return f"""# Model card — card-testing risk model

Generated by `make eval`. Not hand-edited.

## What this is

The one deployed model: a calibrated binary logistic that scores an entity's risk of being card
testing / abuse, **P(abuse)**. It is linear and temperature-scaled, so the request path evaluates it
directly as a few dot products, and its per-feature contributions are exact. The number reported here
is this model's, on a held-out split of the same corpus it was trained on — there is no separate
benchmark model.

- Registry version `{registry.get('version', '?')}`, feature definition `{registry.get('featureDefinitionVersion', '?')}`,
  training data `{registry.get('trainingDataHash', '?')}`.
- {p['n_rows']:,} rows across {p['n_groups']} scenario groups; positive (abuse) rate {p['positive_rate']:.3f}.

## Held-out results

At the cost-optimal block threshold **{h['threshold']:.3f}** (chosen to minimise expected cost from
false-negative ₹{cost['false_negative_paise'] / 100:,.0f} vs false-positive ₹{cost['false_positive_paise'] / 100:,.0f}):

| Metric | Value (95% CI) |
|---|---|
| PR-AUC | {_interval(h['pr_auc'])} |
| Precision | {_interval(h['precision'])} |
| Recall | {_interval(h['recall'])} |
| F1 | {_interval(h['f1'])} |
| ROC-AUC | {h['roc_auc']:.3f} |
| Brier | {h['brier']:.3f} |

No-skill PR-AUC floor (prevalence): {metrics['baseline_no_skill']['pr_auc']:.3f}. Operating point:
false-decline rate {h['false_decline_rate']:.3f}, block-eligible {h['block_rate']:.3f}, review band
{h['review_rate']:.3f} of traffic at a review budget of {h['review_cap']:.3f}.

## Where it is wrong

The per-origin breakdown, hardest first — the honest picture an aggregate hides. The model catches
the obvious attacks and struggles where card testing and a biller's dunning genuinely overlap.

| Origin | Kind | n | Score |
|---|---|---|---|
{per_origin}

## Ablation ladder (PR-AUC)

| Features | Count | PR-AUC |
|---|---|---|
{ablation}

Removing the traffic-context features is what collapses the ability to tell an outage's failures from
a masked attack — the ladder shows it rather than asserting it.

## Leakage delta

Grouped-split PR-AUC {leak['honest_pr_auc']:.3f} vs careless row-wise {leak['naive_pr_auc']:.3f}
(delta {leak['delta']:.3f}). On a corpus from a single seeded generator the gap is small — every
instance generalises to every other — which is the honest thing to report. The dramatic leakage story
belongs to the real-data IEEE-CIS research benchmark, not here.

## What this does not claim

- **These labels are synthetic, not real-world outcomes.** {p['data_note']}
- The model is load-bearing but leashed: it feeds the decision alongside the deterministic rules and
  arbitration, and can route a case to a person, but it never contains a shopper on its own.
"""
