"""The model card for Model B, generated from the metrics so the two cannot disagree."""

from __future__ import annotations


def render_model_card(metrics: dict, registry: dict) -> str:
    p = metrics["provenance"]
    e = metrics["evaluation"]
    h = metrics["hardening"]

    per_class = "\n".join(
        f"| {name} | {m['precision']:.3f} | {m['recall']:.3f} | {m['support']} |"
        for name, m in e["per_class"].items()
    )
    ablation = "\n".join(
        f"| {r['features']} | {r['n_features']} | {r['macro_f1']:.3f} |"
        for r in metrics["ablation_ladder"]
    )
    hard = (
        f"Triggered. Base macro-F1 {h['base_macro_f1']:.3f} exceeded the threshold, so the corpus "
        f"was hardened with feature noise and the model re-scored to macro-F1 "
        f"{h.get('hardened_macro_f1', float('nan')):.3f}. {h.get('note', '')}"
        if h["triggered"]
        else f"Not triggered (base macro-F1 {h['base_macro_f1']:.3f} is below the hardening threshold)."
    )

    return f"""# Model card — incident classifier (Model B)

Generated by `make eval`. Not hand-edited.

## What this is

A calibrated multinomial classifier over the four hypothesis families — attack, outage, retry
storm, healthy traffic — with an explicit **abstain**: below a confidence of {e['abstain_threshold']}
the model declines to decide rather than guess. It is linear and temperature-scaled, so the request
path evaluates it directly as a few dot products, and its per-feature contributions are exact.

- Registry version `{registry.get('version', '?')}`, feature definition `{p['feature_definition_version']}`,
  training data `{p['training_data_hash']}`, ONNX exported: {registry.get('onnxExported', False)}.
- {p['n_rows']:,} rows across {p['n_groups']} scenario groups, trained temperature {p['temperature']:.3f}.

## How it was split

Grouped on the scenario instance, so a seed the model trained on never appears in the test set —
{metrics['split_integrity']['train_test_group_overlap']} groups shared between train and test. A row-
wise shuffle would let it memorise a seed and be rewarded for it.

## Held-out results

Accuracy {e['accuracy']:.3f}, macro-F1 {e['macro_f1']:.3f}, abstain rate {e['abstain_rate']:.3f}.

| Class | Precision | Recall | Support |
|---|---|---|---|
{per_class}

The risk–coverage curve and the four-class confusion matrix are in `metrics.json` and on the
metrics page: as the confidence bar rises the model answers less and is right more of what it does
answer, which is what the abstain buys.

## Ablation ladder

| Features | Count | Macro-F1 |
|---|---|---|
{ablation}

Removing the traffic-context features is what collapses the outage-versus-attack distinction — a per-
entity view cannot tell them apart, and the ladder shows it rather than asserting it.

## Corpus hardening

{hard}

## What this does not claim

- Trained and tested on the scenario corpus, which is synthetic and pre-registered. The classes and
  the method are what transfer; the absolute numbers are a property of the corpus.
- The model is advisory. The deterministic rules and arbitration decide what is *done*; this informs
  that decision and never overrides it.
"""
