#!/usr/bin/env node
/**
 * Writes every scenario to `fixtures/scenarios/`, plus a manifest of what was registered.
 *
 * Committed output, regenerated by running this. Because generation is deterministic, running
 * it twice with no source change produces no diff — which is what makes the manifest a claim
 * rather than a description: a widened range or a changed seed shows up as a changed hash in
 * a reviewable commit, not as noise buried in a thousand regenerated events.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generate, specHash } from './generate.js';
import { SCENARIOS, SCENARIO_FAMILIES } from './spec.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const out = join(root, 'fixtures', 'scenarios');

mkdirSync(out, { recursive: true });

const manifest = SCENARIO_FAMILIES.map((family) => {
  const scenario = generate(family);
  writeFileSync(join(out, `${family}.json`), `${JSON.stringify(scenario, null, 2)}\n`, 'utf8');

  return {
    family,
    seed: scenario.seed,
    specHash: specHash(SCENARIOS[family]),
    classification: scenario.labels.classification,
    counts: scenario.counts,
  };
});

writeFileSync(
  join(out, 'manifest.json'),
  `${JSON.stringify(
    {
      note: 'Pre-registered scenario definitions. Generated by packages/corpus; do not edit by hand.',
      registeredAt: '2026-08-25',
      scenarios: manifest,
    },
    null,
    2,
  )}\n`,
  'utf8',
);

for (const entry of manifest) {
  console.warn(
    `${entry.family.padEnd(22)} seed ${entry.seed}  spec ${entry.specHash}  ` +
      `${entry.counts.orders} orders  ${entry.counts.events} events  ` +
      `${entry.counts.captured} captured  ${entry.counts.failed} failed`,
  );
}
